### ISSUE TITLE
Allow text selection in readme pages

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#142]
### 📝 Provide a description of the new feature

E.g. 

```css
[id^="marketplace"] {
    user-select: text;
}
```
